import Head from "next/head";
import SideNavBar from "../components/sideNavBar";



export default function Home() {
  return (
    <div>
      <Head>
        <title>Starter Kit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pro.ico" />
      </Head>

      <SideNavBar />
    </div>
  );
}
